<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="DESKTOP-JH1F93I"><DocLocation><![CDATA[E:\capgemini\KeywordDrivenFramework\Driver\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res23]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:47]]></Time>
<TimeTick>1648537187</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:47]]></Time>
<TimeTick>1648537187</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:48]]></Time>
<TimeTick>1648537188</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:48]]></Time>
<TimeTick>1648537188</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["6242a99c413dc47f30a5"]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:48]]></Time>
<TimeTick>1648537188</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[WpfButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:48]]></Time>
<TimeTick>1648537188</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" >
<Disp><![CDATA[WpfButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:51]]></Time>
<TimeTick>1648537191</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="21" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:57]]></Time>
<TimeTick>1648537197</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:57]]></Time>
<TimeTick>1648537197</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="25" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="24" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:57]]></Time>
<TimeTick>1648537197</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="30" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["6242a99c413dc47f30a5"]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:57]]></Time>
<TimeTick>1648537197</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="32" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[WpfButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 12:29:58]]></Time>
<TimeTick>1648537198</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" >
<Disp><![CDATA[WpfButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:02]]></Time>
<TimeTick>1648537202</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:02]]></Time>
<TimeTick>1648537202</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="38" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5"]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:02]]></Time>
<TimeTick>1648537202</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="40" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:02]]></Time>
<TimeTick>1648537202</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="42" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:06]]></Time>
<TimeTick>1648537206</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="44" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:12]]></Time>
<TimeTick>1648537212</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:12]]></Time>
<TimeTick>1648537212</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="48" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="47" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:12]]></Time>
<TimeTick>1648537212</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="53" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["6242a99c413dc47f30a5"]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:12]]></Time>
<TimeTick>1648537212</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="55" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[WpfButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:13]]></Time>
<TimeTick>1648537213</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="57" >
<Disp><![CDATA[WpfButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:15]]></Time>
<TimeTick>1648537215</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="59" >
<Disp><![CDATA[WpfTabStrip.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[byNumberRadio.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:15]]></Time>
<TimeTick>1648537215</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="61" >
<Disp><![CDATA[byNumberRadio.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5"]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:15]]></Time>
<TimeTick>1648537215</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="63" >
<Disp><![CDATA[byNumberWatermark.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:16]]></Time>
<TimeTick>1648537216</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="65" >
<Disp><![CDATA[SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[29-03-2022 - 12:30:20]]></Time>
<TimeTick>1648537220</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="67" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="14" status="Passed" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="29-03-2022 - 12:29:40" eTime="29-03-2022 - 12:30:20" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T31">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="29-03-2022 - 12:30:21" eTime="29-03-2022 - 12:30:21" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="69" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T32">
<AName><![CDATA[Action3]]></AName>
<Summary sTime="29-03-2022 - 12:30:21" eTime="29-03-2022 - 12:30:21" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="71" >
<Disp><![CDATA[Action3 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="29-03-2022 - 12:29:39" eTime="29-03-2022 - 12:30:21" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>